# Generated by Django 6.0 on 2025-12-17 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "paternal_last_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Apellido Paterno"
                    ),
                ),
                (
                    "maternal_last_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Apellido Materno",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Fecha de nacimiento")),
                ("gender", models.CharField(max_length=50, verbose_name="Sexo")),
                (
                    "place_of_residence",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Lugar de residencia"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Estado civil"
                    ),
                ),
                (
                    "sexual_orientation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Orientación sexual"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Domicilio")),
                (
                    "landline_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de contacto"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número Celular"
                    ),
                ),
                (
                    "whatsapp_is_mobile",
                    models.BooleanField(
                        default=False, verbose_name="WhatsApp es el mismo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "consultation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de contacto para consulta",
                    ),
                ),
                (
                    "folio_number",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Número de folio",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("note_type", models.CharField(default="general", max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
