# Generated by Django 6.0 on 2025-12-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="category",
            field=models.CharField(
                choices=[
                    ("mood", "Estado de Ánimo"),
                    ("neuro", "Evaluación Neuropsicológica"),
                    ("interview", "Entrevistas"),
                    ("forms", "Formatería"),
                ],
                default="mood",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("depression", "Depresión"),
                    ("anxiety", "Ansiedad"),
                    ("self_harm", "Autolesivos"),
                    ("mental_status", "Estado Mental"),
                    ("executive_functions", "Funciones Ejecutivas"),
                    ("perception", "Percepción"),
                    ("intelligence", "Inteligencia"),
                    ("damage", "Evaluaciones por Daño"),
                    ("clinical", "Clínica"),
                    ("cbt", "Cognitivo Conductual"),
                    ("afc", "AFC"),
                    ("general", "General"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
