# Generated by Django 6.0 on 2025-12-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mood", "Estado de Ánimo"),
                            ("neuro", "Evaluación Neuropsicológica"),
                            ("interview", "Entrevistas"),
                            ("forms", "Formatería"),
                        ],
                        default="mood",
                        max_length=50,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("depression", "Depresión"),
                            ("anxiety", "Ansiedad"),
                            ("self_harm", "Autolesivos"),
                            ("mental_status", "Estado Mental"),
                            ("executive_functions", "Funciones Ejecutivas"),
                            ("perception", "Percepción"),
                            ("intelligence", "Inteligencia"),
                            ("damage", "Evaluaciones por Daño"),
                            ("clinical", "Clínica"),
                            ("cbt", "Cognitivo Conductual"),
                            ("afc", "AFC"),
                            ("general", "General"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Norms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_range_start", models.IntegerField()),
                ("age_range_end", models.IntegerField()),
                ("education_level", models.CharField(max_length=20)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("results", models.JSONField(default=dict)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="patients.patient",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NeuroAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("scores", models.JSONField(default=dict)),
                ("observations", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neuro_assessments",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
